### ISSUE TITLE
Why is SCD-80 not using the standard JEITA SC-80 name?

### ISSUE THREAD

**Issue by evanshultz** [KiCad/Diodes_SMD.pretty#37]
@jkriege2 @SchrodingersGat 

We have an Infineon-specific SCD-80 footprint name, when it appears that standard SC-80 is correct. Anybody know why this is using such a specific name instead of the general, and fully compatible, name?

Infineon datasheet: https://www.infineon.com/dgdl/SCD80-Package_Overview.pdf?fileId=5546d462580663ef0158069ef94f041e

JEITA spec (see page 162, and mind the popups): https://www.pcb-3d.com/wordpress/wp-content/uploads/JEITA_ED-7500A_TC_TB_SC-1_TO_SC-88.pdf

Only the pin width differs, from 0.25mm to 0.3mm, but that doesn't affect the footprint (they're identical) and the physical packages are totally interchangeable on this footprint.

If there are no objections, I'll submit a PR to rename `SCD-80` to `SC-80`.

**Comment by SchrodingersGat** [comment]
The Infineon datasheet also says SC-80. I support this change.
